# Generated by Django 3.2.8 on 2023-01-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('freight_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('Miami-Guamache', 'Miami-Guamache'), ('Miami-La Guaira', 'Miami-La Guaira'), ('Miami-Caracas', 'Miami-Caracas')], max_length=15)),
                ('status', models.CharField(choices=[('En tránsito', 'En tránsito'), ('Retrasado', 'Retrasado'), ('A tiempo', 'A tiempo'), ('En Aduana', 'En Aduana')], max_length=15)),
                ('estimated_date', models.DateField()),
                ('deadline', models.DateField()),
                ('date', models.DateField()),
            ],
        ),
    ]
