# Generated by Django 3.2.8 on 2023-01-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingship',
            old_name='date',
            new_name='deadline_container',
        ),
        migrations.RenameField(
            model_name='trackingship',
            old_name='deadline',
            new_name='departure_date',
        ),
    ]
