# Generated by Django 3.2.8 on 2023-01-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20230110_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingship',
            old_name='estimated_date',
            new_name='estimated_arrived',
        ),
        migrations.AlterField(
            model_name='trackingship',
            name='status',
            field=models.CharField(choices=[('En tránsito', 'En tránsito'), ('Retrasado', 'Retrasado'), ('A tiempo', 'A tiempo'), ('En Aduana', 'En Aduana'), ('Próxima salida', 'Próxima salida')], max_length=15),
        ),
    ]
