# Generated by Django 3.2.8 on 2023-01-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_price_other_citys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingship',
            name='status',
            field=models.CharField(choices=[('En tránsito', 'En tránsito'), ('Retrasado', 'Retrasado'), ('Recibiendo', 'Recibiendo'), ('En Aduana', 'En Aduana'), ('Próxima salida', 'Próxima salida')], max_length=15),
        ),
    ]
