# Generated by Django 3.2.8 on 2023-01-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20230111_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='freight_type',
            new_name='price_aerial',
        ),
        migrations.AddField(
            model_name='price',
            name='price_ship',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
